config/routes.rb
Rails.application.routes.draw do
  resources :tests do
    resources :questions, shallow: true, except: %i[index]
  end
end

app/models/answer.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  body        :text             not null
#  question_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  correct     :boolean          default(FALSE)
#

# :nodoc:
class Answer < ApplicationRecord
  MAX_QUESTION_ANSWERS_COUNT = 4

  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true

  validate :answers_count, on: :create

  private

  def answers_count
    return if question.answers_count >= MAX_QUESTION_ANSWERS_COUNT

    errors.add(:base, "There should be no more than #{MAX_QUESTION_ANSWERS_COUNT} answers to one question")
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# :nodoc:
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

# :nodoc:
class Category < ApplicationRecord
  has_many :tests

  scope :by_title, ->(title) { find_by(title: title) }

  validates :title, presence: true
end

app/models/question.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  body       :text             not null
#  test_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

# :nodoc:
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true

  delegate :title, to: :test, prefix: true
  delegate :count, to: :answer, prefix: true
end

app/models/test.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: tests
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  level       :integer          default(0), not null
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  author_id   :integer
#

# :nodoc:
class Test < ApplicationRecord
  EASY_LEVELS = (0..1).freeze
  MIDDLE_LEVELS = (2..4).freeze
  HARD_LEVELS = (5..Float::INFINITY).freeze

  belongs_to :category
  has_many :questions
  has_many :user_tests
  has_many :users, through: :user_tests
  belongs_to :author, class_name: "User"

  def self.by_category(title)
    Category.by_title(title).tests.order(title: :desc).pluck(:title)
  end
  scope :easy, -> { where(level: EASY_LEVELS) }
  scope :middle, -> { where(level: MIDDLE_LEVELS) }
  scope :hard, -> { where(level: HARD_LEVELS) }

  validates :title, presence: true
  validates :level, numericality: { greater_than: -1 }
  validates :title, uniqueness: { scope: :level }

  # test.category_title -> test.category.title
  delegate :title, to: :category, prefix: true

  delegate :count, to: :questions, prefix: true
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  email      :string           not null
#

class User < ApplicationRecord
  has_many :user_tests
  has_many :tests, through: :user_tests
  has_many :author_tests, class_name: "Test", foreign_key: :author_id

  scope :tests_by_level, ->(level) { tests.where(level: level) }

  validates :email, presence: true
end

app/models/user_test.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: user_tests
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  test_id     :integer
#  finished_at :date
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

##
# @example
# nastya = User.find_by(name: "Nastya")
# UserTest.create(finished_at: 1.day.ago, user: nastya, test: Test.find(4))
# OR
# UserTest.create(finished_at: 1.day.ago, user_id: nastya.id, test: Category.find_by(name: "Cats").tests.first)
# OR
# nastya.user_tests.create(test_id: Test.find(4).id)
class UserTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[show edit update destroy]

  def show; end

  def new
    @question = @test.questions.build
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      render plain: "Question was deleted"
    else
      render plain: "Question was not deleted"
    end
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to "/404.html"
  end

  def find_question
    @question = Question.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to "/404.html"
  end

  def question_params
    params.require(:question).permit(:body)
  end
end

app/controllers/tests_controller.rb
# frozen_string_literal: true

class TestsController < ApplicationController
  before_action :find_test, only: %i[show edit update destroy]

  def index
    @tests = Test.all
  end

  def show
    @questions = @test.questions
  end

  def new
    @test = Test.new
  end

  def create
    @test = author.author_tests.new(test_params)

    if @test.save
      redirect_to @test
    else
      render :new
    end
  end

  def edit; end

  def update
    if @test.update(test_params)
      redirect_to @test
    else
      render :edit
    end
  end

  def destroy
    @test.destroy
    redirect_to tests_path
  end

  private

  def author
    @author ||= User.first
  end

  def find_test
    @test = Test.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to "/404.html"
  end

  def test_params
    params.require(:test).permit(:title, :level, :category_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# :nodoc:
module ApplicationHelper
  def current_year
    # Do not use Date.today without zone. Use Time.zone.today instead
    Time.zone.today.year
  end

  def github_url(author, repo)
    link_to repo, "https://github.com/#{author}/#{repo}", target: "_blank"
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(question)
    test_title = question.test_title
    if question.persisted?
      "Edit #{test_title} Question"
    else
      "Create New #{test_title} Question"
    end
  end
end

app/helpers/tests_helper.rb
# frozen_string_literal: true

module TestsHelper
  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(level)
    TEST_LEVELS[level] || :hero
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/questions/_form.html.erb
<h2><%= question_header(@question) %></h2>
<%= form_with model: [@test, @question] do |form| %>
  <%= form.label :body %>
  <%= form.text_field :body %> 
  <%= form.submit %>
<% end %>

app/views/questions/_question.html.erb
<tr>
  <td><%= link_to question.body, question_path(question) %></td>
  <td><%= link_to "Edit", edit_question_path(question) %><td>
  <td><%= link_to "Delete", question_path(question), method: :delete, data: { confirm: "Are you sure?" } %><td>
</tr>

app/views/questions/edit.html.erb
<%= render "form" %>
<%= link_to "Back", test_path(@question.test) %>

app/views/questions/new.html.erb
<h1>
  <%= "#{@test.id}. #{@test.category.title} - #{@test.title}" %>
</h1>
<h2>
  Create question:
</h2>
<form action="/tests/<%= @test.id %>/questions" method="post">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

  <label for="question-body">Body:</label>
  <input type="text" name="question[body]" id="question-body">
  <input type="submit" value="Create">
</form>

app/views/questions/show.html.erb
<p>
  <%= @question.body %>
</p>
<hr>
<%= link_to "Edit", edit_question_path(@question) %>
<%= link_to "Delete", question_path(@question), method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to "Back", test_path(@question.test) %>

app/views/shared/_footer.html.erb
<hr>
<p>Anastasia Udaltsova, <%= current_year %></p>
<p>GitHub: <%= github_url("udaltsova-nastya", "test_guru") %> -- View and manage tests</p>
<p>Учебный проект в онлайн-школе <%= link_to "Thinknetica", "http://thinknetica.com/", target: "_blank" %></p>